import "@mantine/core/styles.css";
import React from "react";
import {
  MantineProvider,
  ColorSchemeScript,
  mantineHtmlProps,
} from "@mantine/core";
import { theme } from "../theme";
import InstallPWA from "./components/InstallPWA";

export const metadata = {
  title: "Nubrine",
  description: "Nubrine – your mobile-first PWA",
  // The manifest link is auto-generated by Next.js from app/manifest.ts
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent" as const,
    title: "Nubrine",
  },
};

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        {/* Apple touch icon for iOS home-screen */}
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no, viewport-fit=cover"
        />
        <meta name="theme-color" content="#00d4aa" />
      </head>
      <body>
        <MantineProvider theme={theme}>
          {children}
          <InstallPWA />
        </MantineProvider>
      </body>
    </html>
  );
}
